<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // manca la description, name, password, vat, url
        $restaurant= [
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Erboristeria Albero Verde",
                "addres" => "Via Senese, 221-223/rosso",
                "city" => "Galluzzo, FIRENZE",
                "zip" => "50124",
                "email" => "info@alberoverde.net",
                "telephone" => "0552047446",
                "latitude" => "43.749731",
                "longitude" => "11.221211"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "i Toscani",
                "addres" => "Via Maggio 1 R",
                "city" => "FIRENZE",
                "zip" => "50125",
                "email" => "direzione@itoscani.it",
                "telephone" => "055289841",
                "latitude" => "43.767999",
                "longitude" => "11.249737"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "La Cantina",
                "addres" => "Via G. Verga, 28",
                "city" => "055 6121153, FIRENZE",
                "zip" => "50137",
                "email" => "",
                "telephone" => "055 6121153",
                "latitude" => "43.778591",
                "longitude" => "11.296952"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Podere Poggio al Sole",
                "addres" => "Via Santa Reparata 7r",
                "city" => "Trespiano, FIRENZE",
                "zip" => "50139",
                "email" => "info@poderepoggioalsole.com",
                "telephone" => "3272021758",
                "latitude" => "43.77769",
                "longitude" => "11.255632"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Toscana Biologica",
                "addres" => "Via G.B. Foggini, 22",
                "city" => "FIRENZE",
                "zip" => "50142",
                "email" => "tobio@toscanabiologica.it",
                "telephone" => "0557322620",
                "latitude" => "43.771385",
                "longitude" => "11.211845"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "5eCINQUE",
                "addres" => "Piazza DELLA PASSERA 1",
                "city" => "FIRENZE",
                "zip" => "50100",
                "email" => "info@5ecinque.it",
                "telephone" => "+39.055.2741583",
                "latitude" => "43.771033",
                "longitude" => "11.248001"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Accademia dei palati",
                "addres" => "Via Valdinievole 12 FIRENZE",
                "city" => "Novoli, FIRENZE",
                "zip" => "50127",
                "email" => "Mauriziozanolla@accademiadeipalati.it",
                "telephone" => "055412051",
                "latitude" => "43.796242",
                "longitude" => "11.214772"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Aviazione Campo di Marte",
                "addres" => "Viale Malta, 4",
                "city" => "Campo di Marte, FIRENZE",
                "zip" => "50137",
                "email" => "aviazionecampodimarte@virgilio.it",
                "telephone" => "055 5801358",
                "latitude" => "43.776034",
                "longitude" => "11.281521"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Baccarossa",
                "addres" => "Via Ghibellina, 46r",
                "city" => "FIRENZE",
                "zip" => "50122",
                "email" => "info@baccarossa.it",
                "telephone" => "055 240620",
                "latitude" => "43.769516",
                "longitude" => "11.265217"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Bar S.Firenze",
                "addres" => "Piazza San Firenze, 1/r",
                "city" => "FIRENZE",
                "zip" => "",
                "email" => "barsanfirenze@tele2.it",
                "telephone" => "055 211426",
                "latitude" => "43.769751",
                "longitude" => "11.257623"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Bar Trattoria Da Ginone",
                "addres" => "Via dei Serragli, 35/r",
                "city" => "FIRENZE",
                "zip" => "50124",
                "email" => "trattoriaginone@gmail.com",
                "telephone" => "055 218758",
                "latitude" => "43.76729",
                "longitude" => "11.24549"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "BIOVEGGY",
                "addres" => "Via Erbosa 12r",
                "city" => "FIRENZE",
                "zip" => "50100",
                "email" => "info@bioveggy.it",
                "telephone" => "3338359787",
                "latitude" => "43.761185",
                "longitude" => "11.290862"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Boccanegra",
                "addres" => "Via Ghibellina, 124/r",
                "city" => "FIRENZE",
                "zip" => "50122",
                "email" => "info@boccanegra.com",
                "telephone" => "055 2001098",
                "latitude" => "43.770325",
                "longitude" => "11.261361"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Borgo Antico",
                "addres" => "Piazza Santo Spirito, 6/r",
                "city" => "FIRENZE",
                "zip" => "50100",
                "email" => "albertogargelli@alice.it",
                "telephone" => "055 210437",
                "latitude" => "43.766466",
                "longitude" => "11.247524"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Borgo san Jacopo",
                "addres" => "Via Borgo san Jacopo 32/r",
                "city" => "FIRENZE",
                "zip" => "50125",
                "email" => "bsj@lungarnocollection.com",
                "telephone" => "055281661",
                "latitude" => "43.767879",
                "longitude" => "11.251158"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Caff� del '900",
                "addres" => "Borgo Ognissanti, 3/r",
                "city" => "FIRENZE",
                "zip" => "",
                "email" => "caffedel900@aol.it,axcsar@tin.it",
                "telephone" => "055 218390",
                "latitude" => "43.771269",
                "longitude" => "11.247453"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Caff� Le Rose",
                "addres" => "Piazza dell'Unit� Italiana, 1/r",
                "city" => "FIRENZE",
                "zip" => "50123",
                "email" => "a.cursano@alice.it",
                "telephone" => "055 218909",
                "latitude" => "43.775178",
                "longitude" => "11.250307"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "CAFFETTERIA DELLE OBLATE",
                "addres" => "Via dell'Oriuolo 26",
                "city" => "FIRENZE",
                "zip" => "50122",
                "email" => "barbara.setti@archeologia.it",
                "telephone" => "0552639286",
                "latitude" => "43.772345",
                "longitude" => "11.259745"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Cantina Barbagianni",
                "addres" => "Via S. Egidio, 13r",
                "city" => "FIRENZE",
                "zip" => "",
                "email" => "info@cantinabarbagianni.it",
                "telephone" => "055 2480508",
                "latitude" => "43.772335",
                "longitude" => "11.260913"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "CUCO cucina contemporanea",
                "addres" => "Via del melarancio 4/r",
                "city" => "FIRENZE",
                "zip" => "50123",
                "email" => "bencini.stefano@libero.it",
                "telephone" => "347 5217260",
                "latitude" => "43.77475",
                "longitude" => "11.251462"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Da Pescatore Casa di Cucina",
                "addres" => "Piazza del Carmine 7r",
                "city" => "FIRENZE",
                "zip" => "50124",
                "email" => "dp@dapescatore.it",
                "telephone" => "055219978",
                "latitude" => "43.768566",
                "longitude" => "11.244486"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "ENOTRIA ristorante & enoteca",
                "addres" => "Via delle Porte Nuove, 50",
                "city" => "FIRENZE",
                "zip" => "50144",
                "email" => "enotria@enotriawine.it",
                "telephone" => "055354350",
                "latitude" => "43.781293",
                "longitude" => "11.238118"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Fosso Bandito",
                "addres" => "Via Fosso Macinante 2",
                "city" => "FIRENZE",
                "zip" => "50144",
                "email" => "info@fossobandito.com",
                "telephone" => "055365500",
                "latitude" => "43.777474",
                "longitude" => "11.234875"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Giglio Rosso",
                "addres" => "Via Panzani 35 r",
                "city" => "FIRENZE",
                "zip" => "50123",
                "email" => "info@ristorantegigliorosso.com",
                "telephone" => "055 211795",
                "latitude" => "43.773994",
                "longitude" => "11.25116"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Gilda Bistrot",
                "addres" => "Piazza Ghiberti",
                "city" => "FIRENZE",
                "zip" => "50122",
                "email" => "info@gildabistrot.it",
                "telephone" => "0552343885",
                "latitude" => "43.770162",
                "longitude" => "11.266557"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Hostaria Il Desco",
                "addres" => "Via delle Terme 23/r",
                "city" => "FIRENZE",
                "zip" => "",
                "email" => "hostariaildesco@yahoo.it",
                "telephone" => "055/294882",
                "latitude" => "43.769711",
                "longitude" => "11.252901"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Hosteria del Bricco",
                "addres" => "Via S. Niccol?, 8/12",
                "city" => "FIRENZE",
                "zip" => "50126",
                "email" => "info@osteriadelbricco.it",
                "telephone" => "055 2345037",
                "latitude" => "43.7644",
                "longitude" => "11.263822"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Il Pallaio",
                "addres" => "Via Damiano Chiesa, 2",
                "city" => "Campo di Marte, FIRENZE",
                "zip" => "50137",
                "email" => "info@ilpallaio.eu",
                "telephone" => "055 679304",
                "latitude" => "43.774451",
                "longitude" => "11.284546"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Il Povero Pesce",
                "addres" => "Via Pier Fortunato Calvi, 8",
                "city" => "Campo di Marte, FIRENZE",
                "zip" => "50137",
                "email" => "info@poveropesce.it",
                "telephone" => "055 671218",
                "latitude" => "43.774505",
                "longitude" => "11.283521"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Kome Sushi & BBQ Restaurant",
                "addres" => "Via dei Benci, 41r",
                "city" => "FIRENZE",
                "zip" => "50122",
                "email" => "info@komefirenze.it",
                "telephone" => "+39 055 2008009",
                "latitude" => "43.768545",
                "longitude" => "11.260146"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "La Pentola dell'Oro",
                "addres" => "Via di mezzo 22/24/26 R",
                "city" => "FIRENZE",
                "zip" => "50121",
                "email" => "info@lapentoladelloro.it",
                "telephone" => "3332021442",
                "latitude" => "43.771988",
                "longitude" => "11.2647"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "La Pentola dell'Oro",
                "addres" => "Via di Mezzo, 22,24,26 r",
                "city" => "FIRENZE",
                "zip" => "50121",
                "email" => "info@lapentoladelloro.it",
                "telephone" => "055243773",
                "latitude" => "43.771988",
                "longitude" => "11.2647"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "LA STREGA NOCCIOLA - GELATERIA ARTIGIANALE",
                "addres" => "VIA DEI BARDI 51R",
                "city" => "PONTE VECCHIO, FIRENZE",
                "zip" => "50125",
                "email" => "info@lastreganocciola.it",
                "telephone" => "0552382150",
                "latitude" => "43.767057",
                "longitude" => "11.253892"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "La Terrazza del Principe",
                "addres" => "Viale Machiavelli, 10",
                "city" => "FIRENZE",
                "zip" => "50125",
                "email" => "info@laterrazzadelprincipe.com",
                "telephone" => "055 224104",
                "latitude" => "43.762111",
                "longitude" => "11.272616"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Le Campane",
                "addres" => "Borgo La Croce, 87/r",
                "city" => "FIRENZE",
                "zip" => "",
                "email" => "",
                "telephone" => "055 2268667",
                "latitude" => "43.771411",
                "longitude" => "11.267119"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Le Fate",
                "addres" => "Borgo Allegri n.9r",
                "city" => "FIRENZE",
                "zip" => "50100",
                "email" => "ristorantelefate@gmail.com",
                "telephone" => "055/3841998",
                "latitude" => "43.768943",
                "longitude" => "11.263869"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "L'Ortone",
                "addres" => "Piazza ghiberti 87r",
                "city" => "Sant'Ambrogio, FIRENZE",
                "zip" => "50122",
                "email" => "info@lortone.it",
                "telephone" => "055 2340804",
                "latitude" => "43.7706",
                "longitude" => "11.26736"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "L'Osteria Di Giovanni",
                "addres" => "Via del Moro, 22",
                "city" => "FIRENZE",
                "zip" => "50123",
                "email" => "losteriadigiovanni@gmail.com",
                "telephone" => "055 284897",
                "latitude" => "43.771456",
                "longitude" => "11.248557"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "mastro ciliegia ristorante",
                "addres" => "Piazza San Pier maggiore",
                "city" => "FIRENZE",
                "zip" => "50122",
                "email" => "alessandraiozzo@gmail.com",
                "telephone" => "0552480964",
                "latitude" => "43.771342",
                "longitude" => "11.261493"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "MISO di RISO",
                "addres" => "BORGO DEGLI ALBIZI 54R",
                "city" => "FIRENZE",
                "zip" => "50100",
                "email" => "info@misodiriso.it",
                "telephone" => "055 2654094",
                "latitude" => "43.771491",
                "longitude" => "11.260652"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Osteria dei Macci",
                "addres" => "Via dei Macci, 77/r",
                "city" => "FIRENZE",
                "zip" => "",
                "email" => "osteria@osteriadeimacci.it",
                "telephone" => "055 241226",
                "latitude" => "43.770389",
                "longitude" => "11.265959"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Osteria di Giogo",
                "addres" => "Via Chiantigiana 106",
                "city" => "Ponte a Ema, FIRENZE",
                "zip" => "50126",
                "email" => "infi@osteria-giogo.it",
                "telephone" => "0556461311",
                "latitude" => "43.747127",
                "longitude" => "11.294038"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Osteria Gav�",
                "addres" => "Via Lapo da Castiglionchio, 10/12r",
                "city" => "FIRENZE",
                "zip" => "",
                "email" => "",
                "telephone" => "055 6581047",
                "latitude" => "43.76259",
                "longitude" => "11.285842"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Osteria Il Magazzino",
                "addres" => "Piazza della Passera, 2/3",
                "city" => "FIRENZE",
                "zip" => "",
                "email" => "luca_cai@virgilio.it",
                "telephone" => "055 215969",
                "latitude" => "43.767109",
                "longitude" => "11.250566"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Osteria il piacere",
                "addres" => "Via Gabriele d'Annunzio 149",
                "city" => "FIRENZE",
                "zip" => "50135",
                "email" => "info@osteriailpiacere.com",
                "telephone" => "055602605",
                "latitude" => "43.781273",
                "longitude" => "11.301504"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Osteria Re Matto",
                "addres" => "Viale dei mille 152",
                "city" => "FIRENZE",
                "zip" => "50131",
                "email" => "remattofirenze2014@gmail.com",
                "telephone" => "055583851; 3477183636",
                "latitude" => "43.7852",
                "longitude" => "11.27085"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Osteria Santo Spirito",
                "addres" => "Piazza Santo Spirito, 16r",
                "city" => "FIRENZE",
                "zip" => "",
                "email" => "chiarata@interfree.it",
                "telephone" => "055 2382383",
                "latitude" => "43.766435",
                "longitude" => "11.246783"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Piazza del Vino",
                "addres" => "Via della Torretta, 18r",
                "city" => "FIRENZE",
                "zip" => "50137",
                "email" => "piazzadelvino@hotmail.it",
                "telephone" => "055 671404",
                "latitude" => "43.773208",
                "longitude" => "11.282595"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "PizzAudace",
                "addres" => "Via Dosio 77/b",
                "city" => "Legnaia, FIRENZE",
                "zip" => "50142",
                "email" => "pizzaudace@gmail.com",
                "telephone" => "0557135051",
                "latitude" => "43.772858",
                "longitude" => "11.220707"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Plaz Srl",
                "addres" => "Via Pietrapiana, 36r",
                "city" => "FIRENZE",
                "zip" => "",
                "email" => "pierluigiurbini@hotmail.com",
                "telephone" => "055 242081",
                "latitude" => "43.771421",
                "longitude" => "11.263638"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Rio Freddo",
                "addres" => "Viale Giovan Battista Morgagni 12a",
                "city" => "FIRENZE",
                "zip" => "50134",
                "email" => "riofreddo.fi@gmail.com",
                "telephone" => "055416945",
                "latitude" => "43.797825",
                "longitude" => "11.242668"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Ristorante \"Accademia\"",
                "addres" => "Piazza S. Marco, 7/r",
                "city" => "FIRENZE",
                "zip" => "50121",
                "email" => "",
                "telephone" => "055 217343",
                "latitude" => "43.777735",
                "longitude" => "11.25845"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Ristorante \"All'Antico Ristoro di Cambi\"",
                "addres" => "Via S. Onofrio, 1/r",
                "city" => "FIRENZE",
                "zip" => "50125",
                "email" => "info@anticoristorodicambi.it",
                "telephone" => "055 217134",
                "latitude" => "43.770426",
                "longitude" => "11.24202"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Ristorante Bacca Rossa",
                "addres" => "Via Ghibellina 46/r",
                "city" => "FIRENZE",
                "zip" => "",
                "email" => "info@baccarossa.it",
                "telephone" => "055/240620",
                "latitude" => "43.769519",
                "longitude" => "11.26501"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Ristorante Cavolo Nero",
                "addres" => "Via dell'Ardiglione, 22",
                "city" => "FIRENZE",
                "zip" => "",
                "email" => "cavolonero@cavolonero.it",
                "telephone" => "055 294744",
                "latitude" => "43.767452",
                "longitude" => "11.244982"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Ristorante \"Da Burde\"",
                "addres" => "Via Pistoiese, 6/r",
                "city" => "FIRENZE",
                "zip" => "50145",
                "email" => "info@daburde.it",
                "telephone" => "055 317206",
                "latitude" => "43.795897",
                "longitude" => "11.20349"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Ristorante Da Lino",
                "addres" => "Via Santa Elisabetta, 6/r",
                "city" => "FIRENZE",
                "zip" => "50122",
                "email" => "ristdalino@virgilio.it",
                "telephone" => "055 284579",
                "latitude" => "43.771721",
                "longitude" => "11.256091"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Ristorante Enoteca \"Il Portale\"",
                "addres" => "Via Alamanni,D29",
                "city" => "FIRENZE",
                "zip" => "50100",
                "email" => "",
                "telephone" => "055 289767",
                "latitude" => "43.775895",
                "longitude" => "11.247214"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Ristorante \"Enzo e Piero\"",
                "addres" => "Via Faenza, 105/R",
                "city" => "FIRENZE",
                "zip" => "50123",
                "email" => "enzoepiero@hotmail.com",
                "telephone" => "055 214901",
                "latitude" => "43.77888",
                "longitude" => "11.250398"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Ristorante \"Giannino in S. Lorenzo\" di Bartoloni R. & C. sas",
                "addres" => "Via Borgo S. Lorenzo, 35/37r",
                "city" => "FIRENZE",
                "zip" => "50100",
                "email" => "info@gianninoinflorence.com",
                "telephone" => "+39 055 239.97.99",
                "latitude" => "43.774315",
                "longitude" => "11.254889"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Ristorante \"Grotta Guelfa\"",
                "addres" => "Via Pellicceria, 5/r",
                "city" => "FIRENZE",
                "zip" => "50100",
                "email" => "info@grottaguelfa.it",
                "telephone" => "055 268041",
                "latitude" => "43.77008",
                "longitude" => "11.253562"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Ristorante Gustavino",
                "addres" => "Via della Condotta, 29/37r",
                "city" => "FIRENZE",
                "zip" => "",
                "email" => "www.gustavino.it",
                "telephone" => "055 2399806",
                "latitude" => "43.770203",
                "longitude" => "11.25679"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Ristorante I Ghibellini",
                "addres" => "Piazza S.P.Maggiore, 8/10r",
                "city" => "FIRENZE",
                "zip" => "",
                "email" => "info@ighibellini.com",
                "telephone" => "055 214424",
                "latitude" => "43.771462",
                "longitude" => "11.261437"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Ristorante Il Paiolo",
                "addres" => "Via del Corso 42/r",
                "city" => "FIRENZE",
                "zip" => "50122",
                "email" => "info@ristoranteilpaiolo.it",
                "telephone" => "055/215019",
                "latitude" => "43.771487",
                "longitude" => "11.256336"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Ristorante \"I Quattro Amici\"",
                "addres" => "Via Orti Oricellari, 29",
                "city" => "FIRENZE",
                "zip" => "50123",
                "email" => "quattroamici@accademiadelgusto.it",
                "telephone" => "055 212992",
                "latitude" => "43.776617",
                "longitude" => "11.246077"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Ristorante \"I' Toscano\"",
                "addres" => "Via Guelfa, 70/r",
                "city" => "FIRENZE",
                "zip" => "50100",
                "email" => "info@itoscano.it",
                "telephone" => "055 215475",
                "latitude" => "43.778326",
                "longitude" => "11.252984"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Ristorante La Bocca di Leone",
                "addres" => "Via Pisana 41 rosso",
                "city" => "FIRENZE",
                "zip" => "50143",
                "email" => "info@laboccadileone.it",
                "telephone" => "0552286572",
                "latitude" => "43.765041",
                "longitude" => "11.20988"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Ristorante La Falterona",
                "addres" => "Via G.B. Zannoni, 10/12r",
                "city" => "FIRENZE",
                "zip" => "",
                "email" => "claudioconsole@hotmail.com",
                "telephone" => "055 216112",
                "latitude" => "43.776698",
                "longitude" => "11.252391"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Ristorante La Frasca",
                "addres" => "Via Faentina, 70r",
                "city" => "FIRENZE",
                "zip" => "",
                "email" => "lafrasca@tiscali.it",
                "telephone" => "055 571244",
                "latitude" => "43.788473",
                "longitude" => "11.266522"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "RISTORANTE LA MARTINICCA",
                "addres" => "Via del Sole 27/r",
                "city" => "FIRENZE",
                "zip" => "50100",
                "email" => "info@ristorante-lamartinicca.com",
                "telephone" => "055-218928",
                "latitude" => "43.772351",
                "longitude" => "11.249973"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Ristorante \"Michelaccio\"",
                "addres" => "Via Ponte di Mezzo, 11-13-15/r",
                "city" => "FIRENZE",
                "zip" => "50127",
                "email" => "",
                "telephone" => "055 332495",
                "latitude" => "43.791444",
                "longitude" => "11.237122"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Ristorante \"Olio & Convivium\"",
                "addres" => "Via S. Spirito, 4",
                "city" => "FIRENZE",
                "zip" => "50100",
                "email" => "olio.convivium@conviviumfirenze.it",
                "telephone" => "055 2656267",
                "latitude" => "43.768188",
                "longitude" => "11.249624"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Ristorante Palazzo Tempi",
                "addres" => "Via dei Bardi, 33/37",
                "city" => "FIRENZE",
                "zip" => "",
                "email" => "",
                "telephone" => "055 2466949",
                "latitude" => "43.76651",
                "longitude" => "11.255045"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Ristorante Pizzeria \"La Grotta di Leo\"",
                "addres" => "Via della Scala, 41-43/r",
                "city" => "FIRENZE",
                "zip" => "50123",
                "email" => "",
                "telephone" => "055 264413",
                "latitude" => "43.774861",
                "longitude" => "11.246567"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Ristorante Rio Freddo",
                "addres" => "Viale G.B. Morgagni 10b-12a",
                "city" => "FIRENZE",
                "zip" => "50134",
                "email" => "riofreddo.fi@gmail.it",
                "telephone" => "055416945",
                "latitude" => "43.797825",
                "longitude" => "11.242668"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Ristorante Sabatini",
                "addres" => "Via Panzani, 9A",
                "city" => "FIRENZE",
                "zip" => "50123",
                "email" => "info@ristorantesabatini.it",
                "telephone" => "055 211559",
                "latitude" => "43.774232",
                "longitude" => "11.25079"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Ristorante Vecchio Casale",
                "addres" => "Via delle Torri, 7",
                "city" => "FIRENZE",
                "zip" => "50142",
                "email" => "info@ristorante-vecchiocasale.com",
                "telephone" => "055 7326162",
                "latitude" => "43.777139",
                "longitude" => "11.205073"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Tea 3 Srl",
                "addres" => "Via Lanza, 54",
                "city" => "FIRENZE",
                "zip" => "",
                "email" => "",
                "telephone" => "",
                "latitude" => "43.768218",
                "longitude" => "11.281993"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "TIRABARALLA",
                "addres" => "VIA DELLA SCALA, 28R",
                "city" => "FIRENZE",
                "zip" => "50123",
                "email" => "info@tirabaralla.it",
                "telephone" => "055.218.418",
                "latitude" => "43.775222",
                "longitude" => "11.246087"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Trattoria Boboli",
                "addres" => "Via Romana 45 r",
                "city" => "FIRENZE",
                "zip" => "",
                "email" => "trattoriaboboli@gmail.com",
                "telephone" => "055 2336401",
                "latitude" => "43.76408",
                "longitude" => "11.246139"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Trattoria Celestino",
                "addres" => "Piazza Santa Felice, 4r",
                "city" => "FIRENZE",
                "zip" => "",
                "email" => "bruno.celestino@virgilio.it",
                "telephone" => "055 2396574",
                "latitude" => "43.764898",
                "longitude" => "11.24789"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Trattoria da Beppino",
                "addres" => "Via di Ripoli 13/r",
                "city" => "FIRENZE",
                "zip" => "50126",
                "email" => "trattoriabeppino@gmail.com",
                "telephone" => "0556810505",
                "latitude" => "43.762757",
                "longitude" => "11.278902"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Trattoria da garibardi",
                "addres" => "Piazza del mercato centrale 38r",
                "city" => "FIRENZE",
                "zip" => "50123",
                "email" => "info@garibardi.it",
                "telephone" => "055212267",
                "latitude" => "43.77656",
                "longitude" => "11.254013"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Trattoria La Gratella",
                "addres" => "Via Guelfa, 81r",
                "city" => "FIRENZE",
                "zip" => "50129",
                "email" => "ferrara.daniela@hotmail.it",
                "telephone" => "055 211292",
                "latitude" => "43.778661",
                "longitude" => "11.252008"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Trattoria La Madia",
                "addres" => "Via del Giglio, 14/r",
                "city" => "FIRENZE",
                "zip" => "50139",
                "email" => "trattorialamadiafi@alice.it",
                "telephone" => "055 218563",
                "latitude" => "43.7741",
                "longitude" => "11.251553"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "TRATTORIA OMERO",
                "addres" => "VIA PIAN DEI GIULLARI 11/R",
                "city" => "Arcetri, FIRENZE",
                "zip" => "50125",
                "email" => "omero@ristoranteomero.it",
                "telephone" => "055220053",
                "latitude" => "43.751175",
                "longitude" => "11.256254"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "Trattoria Palle d'Oro",
                "addres" => "Via Sant'Antonino 43-45/r",
                "city" => "FIRENZE",
                "zip" => "50123",
                "email" => "trattoriapalledoro@gmail.com",
                "telephone" => "055 288383",
                "latitude" => "43.775874",
                "longitude" => "11.25275"
            ],
            [
                "municipality" => "Firenze",
                "province" => "FIRENZE",
                "city"=>"Firenze",
                "activity_name" => "VECCHIA FIRENZE",
                "addres" => "Borgo Albizi 18 / 76 r",
                "city" => "FIRENZE",
                "zip" => "50122",
                "email" => "vecchia.firenze@libero.it",
                "telephone" => "055 - 2340361 - 2",
                "latitude" => "43.771332",
                "longitude" => "11.261867"
            ],








        ]
    }
}
